version: '3'
networks:
  panel:
volumes:
  panelfile:
    driver: local
  db:
    driver: local
services:
  web:
    container_name: web
    image: rogolezhou/nginx1215
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/nginx/config:/etc/nginx/conf.d
  php:
    container_name: php
    image: rogolezhou/php74-fpm:panel
    volumes:
      - panelfile:/mnt/app/www
      - /etc/localtime:/etc/localtime
    networks:
      - panel
    tty: true
  db:
    container_name: db
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - panel
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - panel
    environment:
      PMA_HOST: "db"
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
